export default {
  NOT_FOUND: "/404",
  SIGN_IN: "/zaloguj-sie",
  SIGN_UP: "/zaloz-konto",
  VERIFY: "/weryfikacja",
  MY_DOCUMENTS: "/moje-dokumenty",
  DOCUMENTS: "/dokumenty",
  TOS: "/regulamin",
  IDENTITIES: "/tozsamosci",
  BLOG: "/blog",
  ORDER: "/zamowienie",
  DOCUMENT: "/dokument",
  RESET_PASSWORD: "/reset-hasla",
  SET_PASSWORD: "/reset-hasla/nowe-haslo",
  PROFILE: "/profil",
  HOME: "/",
  SUMMARY: "/podsumowanie",
};
