export default {
  address: "02-001 Warszawa, Aleje Jerozolimskie 91",
  apt: 7,
  area: 100,
  room: 3,
  kitchen: 1,
  hall: 1,
  bathroom: 1,
  toilet: 1,
  wardrobe: 0,
  garage: 0,
  systems: "elektryczna, gazowa, centralne ogrzewanie",
  equipment:
    "Toster Philips o nr seryjnym XBSDCS89734-2342234, dwa fotele, kanapa",
  purpose: "do celów mieszkalnych",
  rent: 2300,
  rentmethod: "płatny przelewem na konto Wynajmującego",
  rentdue: 14,
  billslandlord: "zużycie energii, zużycie gazu, zużycie wody, wywóz śmieci",
  billstenant: "opłata za internet, opłata telewizyjna",
  deposit: 2300,
  depositmethod: "płatna przelewem na konto Wynajmującego",
  repairs: 2500,
  termination: 14,
  return: 14,
};
